CREATE TABLE [dbo].[MRI_Bldg] (
    [BldgId]              CHAR (6)        NOT NULL,
    [BldgName]            CHAR (40)       NULL,
    [City]                CHAR (30)       NULL,
    [State]               CHAR (3)        NULL,
    [ZipCode]             CHAR (9)        NULL,
    [LlrdId]              CHAR (6)        NOT NULL,
    [PayTo]               CHAR (30)       NULL,
    [Bldggla]             MONEY           NULL,
    [Sdintrst]            MONEY           NULL,
    [Address1]            CHAR (50)       NULL,
    [Address2]            CHAR (30)       NULL,
    [PhoneNo]             CHAR (15)       NULL,
    [BillDate]            DATETIME        NULL,
    [NmbrUnit]            INT             NULL,
    [MngrId]              CHAR (6)        NOT NULL,
    [Mgrstdat]            DATETIME        NULL,
    [Mgrexdat]            DATETIME        NULL,
    [Prtstat]             CHAR (1)        NOT NULL,
    [DayDue]              SMALLINT        NULL,
    [DelqDay]             SMALLINT        NULL,
    [DelqOpt]             CHAR (1)        NULL,
    [LateFlat]            MONEY           NULL,
    [LateRate]            FLOAT (53)      NULL,
    [LateCalc]            CHAR (1)        NULL,
    [MgmtRate]            FLOAT (53)      NULL,
    [NcFlag]              CHAR (1)        NOT NULL,
    [LastDate]            DATETIME        NULL,
    [UserId]              CHAR (20)       NULL,
    [Inactive]            CHAR (1)        NOT NULL,
    [ICashTyp]            CHAR (2)        NULL,
    [DCashTyp]            CHAR (2)        NULL,
    [CpiIndex]            CHAR (4)        NULL,
    [PtwId]               CHAR (4)        NULL,
    [EntityId]            CHAR (6)        NOT NULL,
    [AltAddr1]            CHAR (50)       NULL,
    [AltAddr2]            CHAR (50)       NULL,
    [AltCity]             CHAR (30)       NULL,
    [AltState]            CHAR (3)        NULL,
    [AltZip]              CHAR (9)        NULL,
    [CloseDay]            CHAR (3)        NOT NULL,
    [FedidTyp]            CHAR (1)        NOT NULL,
    [Feemeth]             CHAR (1)        NOT NULL,
    [FlatAmt]             MONEY           NULL,
    [MgmtAcc]             CHAR (12)       NULL,
    [MgmtCash]            CHAR (2)        NULL,
    [RefndAcc]            CHAR (12)       NULL,
    [Refndcas]            CHAR (2)        NULL,
    [SecurAcc]            CHAR (12)       NULL,
    [Securcas]            CHAR (2)        NULL,
    [County]              CHAR (15)       NULL,
    [AltCount]            CHAR (15)       NULL,
    [ProcDate]            DATETIME        NULL,
    [Cmintrac]            CHAR (12)       NULL,
    [OccSuite]            INT             NULL,
    [Occgla]              MONEY           NULL,
    [GlDetail]            CHAR (1)        NOT NULL,
    [StartInv]            INT             NULL,
    [Fasb13]              CHAR (1)        NOT NULL,
    [SqftType]            CHAR (3)        NULL,
    [Fasbstrt]            DATETIME        NULL,
    [Profile]             CHAR (2)        NULL,
    [WoIncCat]            CHAR (3)        NULL,
    [MarkUp]              MONEY           NULL,
    [MincCat]             CHAR (3)        NULL,
    [TickForm]            CHAR (2)        NULL,
    [ScanCodeId]          CHAR (3)        NULL,
    [Rptypri1]            CHAR (3)        NULL,
    [Rptypri2]            CHAR (3)        NULL,
    [Rptypri3]            CHAR (3)        NULL,
    [Rptypri4]            CHAR (3)        NULL,
    [Rptypri5]            CHAR (3)        NULL,
    [BilLevel]            CHAR (3)        NULL,
    [EstLevel]            CHAR (3)        NULL,
    [RecLevel]            CHAR (3)        NULL,
    [Natural]             CHAR (1)        NOT NULL,
    [NincCat1]            CHAR (3)        NULL,
    [NincCat2]            CHAR (3)        NULL,
    [NincCat3]            CHAR (3)        NULL,
    [Estmeth]             CHAR (3)        NULL,
    [BillPnt]             CHAR (1)        NOT NULL,
    [Calcest]             CHAR (1)        NOT NULL,
    [Reqrpty]             CHAR (3)        NULL,
    [ForeType]            CHAR (3)        NULL,
    [PercChng]            MONEY           NULL,
    [Retail]              CHAR (1)        NULL,
    [NrecId]              CHAR (6)        NULL,
    [Basis]               CHAR (1)        NULL,
    [Mgmtnont]            CHAR (1)        NULL,
    [Mgmtsecapp]          CHAR (1)        NULL,
    [Mgmtcrapp]           CHAR (1)        NULL,
    [MgmtVendId]          CHAR (6)        NULL,
    [LtfeeDays]           SMALLINT        NULL,
    [LtfcAmt]             MONEY           NULL,
    [CarPark]             SMALLINT        NULL,
    [Mobile]              CHAR (15)       NULL,
    [Fax]                 CHAR (15)       NULL,
    [Email]               CHAR (35)       NULL,
    [ContName]            CHAR (30)       NULL,
    [RangeType]           CHAR (1)        NULL,
    [MgmtDept]            CHAR (3)        NULL,
    [MgmtrTaxGrp]         CHAR (1)        NULL,
    [PropId]              CHAR (3)        NULL,
    [Revmethod1]          CHAR (5)        NULL,
    [ReviewDate]          DATETIME        NULL,
    [Recovered]           CHAR (3)        NULL,
    [MgmtAct]             CHAR (1)        NULL,
    [BatchName]           CHAR (10)       NULL,
    [InactiveDate]        CHAR (6)        NULL,
    [Autoreport]          CHAR (1)        NULL,
    [MgmtBillflat]        CHAR (1)        NULL,
    [Days]                FLOAT (53)      NOT NULL,
    [OwnCopy]             CHAR (1)        NULL,
    [AltMngrId]           CHAR (6)        NULL,
    [ReportBasis]         CHAR (1)        NULL,
    [SscStaffId]          CHAR (6)        NULL,
    [ProRata]             CHAR (1)        NULL,
    [OType]               CHAR (2)        NULL,
    [FoBldg]              CHAR (1)        NULL,
    [Class]               CHAR (6)        NULL,
    [MerchantId]          CHAR (6)        NULL,
    [MerchantPassword]    CHAR (8)        NULL,
    [RecpttypeId]         CHAR (3)        NULL,
    [BApplyByPriority]    CHAR (1)        NULL,
    [URL]                 CHAR (50)       NULL,
    [AttachId]            CHAR (8)        NULL,
    [Agent]               CHAR (10)       NULL,
    [CommenceDate]        CHAR (6)        NULL,
    [LastmngrId]          CHAR (6)        NULL,
    [ReasonCode]          CHAR (4)        NULL,
    [Ifrsenable]          CHAR (1)        NULL,
    [Ownership]           CHAR (5)        NULL,
    [Mgmtcomm]            TEXT            NULL,
    [BldgMatrixOption]    CHAR (1)        NULL,
    [MatrixId]            FLOAT (53)      NULL,
    [Trns_Dttm]           DATETIME        NULL,
    [ProdCode]            CHAR (2)        NOT NULL,
    [EnviroFlag]          CHAR (1)        NULL,
    [Baseuom]             CHAR (6)        NULL,
    [Alternateuom]        CHAR (6)        NULL,
    [UseAlternateuom]     CHAR (1)        NULL,
    [FedId]               VARBINARY (MAX) NULL,
    [Map]                 CHAR (500)      NULL,
    [BCatId]              CHAR (7)        NULL,
    [FmChk]               CHAR (1)        NULL,
    [PmChk]               CHAR (1)        NULL,
    [FinChk]              CHAR (1)        NULL,
    [FmNote]              CHAR (50)       NULL,
    [PmNote]              CHAR (50)       NULL,
    [FinNote]             CHAR (50)       NULL,
    [OwnType]             CHAR (10)       NULL,
    [ClarityBldg]         CHAR (1)        NULL,
    [CCouncil]            CHAR (40)       NULL,
    [PropSubType]         CHAR (3)        NULL,
    [SrvcCred]            CHAR (12)       NULL,
    [SrvcDebt]            CHAR (12)       NULL,
    [AllowPartPmnt]       CHAR (1)        DEFAULT ('N') NULL,
    [AllowCredit]         CHAR (1)        DEFAULT ('N') NULL,
    [AllowCreditApply]    CHAR (1)        DEFAULT ('N') NULL,
    [LogoRef]             VARCHAR (50)    NULL,
    [AchProvider]         CHAR (20)       NULL,
    [CcProvider]          CHAR (20)       NULL,
    [ReccProvider]        CHAR (20)       NULL,
    [InvoiceTo]           CHAR (100)      NULL,
    [Site]                CHAR (20)       NULL,
    [StmtType]            CHAR (10)       NULL,
    [DisplayProviderLogo] CHAR (1)        DEFAULT ('Y') NOT NULL,
    [RapidBldg]           CHAR (1)        NULL,
    [RapidDate]           DATETIME        NULL,
    [MgmtAggr]            CHAR (12)       NULL,
    [Measurbl]            CHAR (1)        NULL,
    [Well]                CHAR (1)        NULL,
    [Country]             CHAR (15)       NULL,
    [BldgUse]             CHAR (15)       NULL,
    [FmOnly]              CHAR (1)        NULL,
    [UrbBldg]             CHAR (1)        NULL,
    [SegmentId]           CHAR (10)       NULL,
    [Plalloc]             CHAR (10)       NULL,
    CONSTRAINT [Upkcl_Bldg] PRIMARY KEY CLUSTERED ([BldgId] ASC)
);

