/*
Deployment script for Database1

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Database1"
:setvar DefaultFilePrefix "Database1"
:setvar DefaultDataPath "C:\Users\Jobin\AppData\Local\Microsoft\VisualStudio\SSDT\Database1"
:setvar DefaultLogPath "C:\Users\Jobin\AppData\Local\Microsoft\VisualStudio\SSDT\Database1"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                CURSOR_DEFAULT LOCAL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE,
                DISABLE_BROKER 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Creating User [test01]...';


GO
CREATE USER [test01] FOR LOGIN [Test01];


GO
REVOKE CONNECT TO [test01];


GO
PRINT N'Creating User [test03]...';


GO
CREATE USER [test03] FOR LOGIN [test03];


GO
REVOKE CONNECT TO [test03];


GO
PRINT N'Creating Role Membership [db_owner] for [test03]...';


GO
EXECUTE sp_addrolemember @rolename = N'db_owner', @membername = N'test03';


GO
PRINT N'Creating Table [dbo].[azureparameters]...';


GO
CREATE TABLE [dbo].[azureparameters] (
    [getURL]                    NVARCHAR (MAX) NULL,
    [sinkfolderpath]            NVARCHAR (MAX) NULL,
    [lastmodifiedtime]          NVARCHAR (MAX) NULL,
    [sql_tablename]             NVARCHAR (50)  NOT NULL,
    [adf_pipeline_name]         NVARCHAR (MAX) NULL,
    [subscription_id]           NVARCHAR (MAX) NULL,
    [client_id_reference]       NVARCHAR (MAX) NULL,
    [client_secret_reference]   NVARCHAR (MAX) NULL,
    [app_key_reference]         NVARCHAR (MAX) NULL,
    [rg_name]                   NVARCHAR (MAX) NULL,
    [adf_name]                  NVARCHAR (MAX) NULL,
    [lapp_servicetitan_api_URL] NVARCHAR (MAX) NULL,
    [Is_Active]                 NVARCHAR (MAX) NULL,
    [PipelineParamsJson]        NVARCHAR (MAX) NULL,
    [key_vault_name]            VARCHAR (255)  NULL,
    [timezone]                  NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([sql_tablename] ASC)
);


GO
PRINT N'Creating Table [dbo].[''Building $'']...';


GO
CREATE TABLE [dbo].['Building $'] (
    [BldgId]              FLOAT (53)     NULL,
    [BldgName]            NVARCHAR (255) NULL,
    [City]                NVARCHAR (255) NULL,
    [State]               NVARCHAR (255) NULL,
    [ZipCode]             NVARCHAR (255) NULL,
    [LlrdId]              NVARCHAR (255) NULL,
    [PayTo]               NVARCHAR (255) NULL,
    [Bldggla]             FLOAT (53)     NULL,
    [Sdintrst]            NVARCHAR (255) NULL,
    [Address1]            NVARCHAR (255) NULL,
    [Address2]            NVARCHAR (255) NULL,
    [PhoneNo]             NVARCHAR (255) NULL,
    [BillDate]            DATETIME       NULL,
    [NmbrUnit]            FLOAT (53)     NULL,
    [MngrId]              NVARCHAR (255) NULL,
    [Mgrstdat]            NVARCHAR (255) NULL,
    [Mgrexdat]            NVARCHAR (255) NULL,
    [Prtstat]             NVARCHAR (255) NULL,
    [DayDue]              FLOAT (53)     NULL,
    [DelqDay]             FLOAT (53)     NULL,
    [DelqOpt]             NVARCHAR (255) NULL,
    [LateFlat]            NVARCHAR (255) NULL,
    [LateRate]            NVARCHAR (255) NULL,
    [LateCalc]            NVARCHAR (255) NULL,
    [MgmtRate]            NVARCHAR (255) NULL,
    [NcFlag]              NVARCHAR (255) NULL,
    [LastDate]            DATETIME       NULL,
    [UserId]              NVARCHAR (255) NULL,
    [Inactive]            NVARCHAR (255) NULL,
    [ICashTyp]            NVARCHAR (255) NULL,
    [DCashTyp]            NVARCHAR (255) NULL,
    [CpiIndex]            NVARCHAR (255) NULL,
    [PtwId]               NVARCHAR (255) NULL,
    [EntityId]            FLOAT (53)     NULL,
    [AltAddr1]            NVARCHAR (255) NULL,
    [AltAddr2]            NVARCHAR (255) NULL,
    [AltCity]             NVARCHAR (255) NULL,
    [AltState]            NVARCHAR (255) NULL,
    [AltZip]              NVARCHAR (255) NULL,
    [CloseDay]            NVARCHAR (255) NULL,
    [FedidTyp]            FLOAT (53)     NULL,
    [Feemeth]             NVARCHAR (255) NULL,
    [FlatAmt]             NVARCHAR (255) NULL,
    [MgmtAcc]             NVARCHAR (255) NULL,
    [MgmtCash]            NVARCHAR (255) NULL,
    [RefndAcc]            NVARCHAR (255) NULL,
    [Refndcas]            NVARCHAR (255) NULL,
    [SecurAcc]            NVARCHAR (255) NULL,
    [Securcas]            NVARCHAR (255) NULL,
    [County]              NVARCHAR (255) NULL,
    [AltCount]            NVARCHAR (255) NULL,
    [ProcDate]            DATETIME       NULL,
    [Cmintrac]            NVARCHAR (255) NULL,
    [OccSuite]            FLOAT (53)     NULL,
    [Occgla]              FLOAT (53)     NULL,
    [GlDetail]            NVARCHAR (255) NULL,
    [StartInv]            FLOAT (53)     NULL,
    [Fasb13]              NVARCHAR (255) NULL,
    [SqftType]            NVARCHAR (255) NULL,
    [Fasbstrt]            NVARCHAR (255) NULL,
    [Profile]             NVARCHAR (255) NULL,
    [WoIncCat]            NVARCHAR (255) NULL,
    [MarkUp]              NVARCHAR (255) NULL,
    [MincCat]             NVARCHAR (255) NULL,
    [TickForm]            NVARCHAR (255) NULL,
    [ScanCodeId]          NVARCHAR (255) NULL,
    [Rptypri1]            NVARCHAR (255) NULL,
    [Rptypri2]            NVARCHAR (255) NULL,
    [Rptypri3]            NVARCHAR (255) NULL,
    [Rptypri4]            NVARCHAR (255) NULL,
    [Rptypri5]            NVARCHAR (255) NULL,
    [BilLevel]            NVARCHAR (255) NULL,
    [EstLevel]            NVARCHAR (255) NULL,
    [RecLevel]            NVARCHAR (255) NULL,
    [Natural]             NVARCHAR (255) NULL,
    [NincCat1]            NVARCHAR (255) NULL,
    [NincCat2]            NVARCHAR (255) NULL,
    [NincCat3]            NVARCHAR (255) NULL,
    [Estmeth]             NVARCHAR (255) NULL,
    [BillPnt]             NVARCHAR (255) NULL,
    [Calcest]             NVARCHAR (255) NULL,
    [Reqrpty]             NVARCHAR (255) NULL,
    [ForeType]            NVARCHAR (255) NULL,
    [PercChng]            NVARCHAR (255) NULL,
    [Retail]              NVARCHAR (255) NULL,
    [NrecId]              NVARCHAR (255) NULL,
    [Basis]               NVARCHAR (255) NULL,
    [Mgmtnont]            NVARCHAR (255) NULL,
    [Mgmtsecapp]          NVARCHAR (255) NULL,
    [Mgmtcrapp]           NVARCHAR (255) NULL,
    [MgmtVendId]          FLOAT (53)     NULL,
    [LtfeeDays]           FLOAT (53)     NULL,
    [LtfcAmt]             NVARCHAR (255) NULL,
    [CarPark]             FLOAT (53)     NULL,
    [Mobile]              NVARCHAR (255) NULL,
    [Fax]                 NVARCHAR (255) NULL,
    [Email]               NVARCHAR (255) NULL,
    [ContName]            NVARCHAR (255) NULL,
    [RangeType]           NVARCHAR (255) NULL,
    [MgmtDept]            NVARCHAR (255) NULL,
    [MgmtrTaxGrp]         NVARCHAR (255) NULL,
    [PropId]              NVARCHAR (255) NULL,
    [Revmethod1]          NVARCHAR (255) NULL,
    [ReviewDate]          NVARCHAR (255) NULL,
    [Recovered]           NVARCHAR (255) NULL,
    [MgmtAct]             NVARCHAR (255) NULL,
    [BatchName]           NVARCHAR (255) NULL,
    [InactiveDate]        NVARCHAR (255) NULL,
    [Autoreport]          NVARCHAR (255) NULL,
    [MgmtBillflat]        NVARCHAR (255) NULL,
    [Days]                FLOAT (53)     NULL,
    [OwnCopy]             NVARCHAR (255) NULL,
    [AltMngrId]           NVARCHAR (255) NULL,
    [ReportBasis]         NVARCHAR (255) NULL,
    [SscStaffId]          NVARCHAR (255) NULL,
    [ProRata]             NVARCHAR (255) NULL,
    [OType]               NVARCHAR (255) NULL,
    [FoBldg]              NVARCHAR (255) NULL,
    [Class]               NVARCHAR (255) NULL,
    [MerchantId]          NVARCHAR (255) NULL,
    [MerchantPassword]    NVARCHAR (255) NULL,
    [RecpttypeId]         NVARCHAR (255) NULL,
    [BApplyByPriority]    NVARCHAR (255) NULL,
    [URL]                 NVARCHAR (255) NULL,
    [AttachId]            NVARCHAR (255) NULL,
    [Agent]               NVARCHAR (255) NULL,
    [CommenceDate]        NVARCHAR (255) NULL,
    [LastmngrId]          NVARCHAR (255) NULL,
    [ReasonCode]          NVARCHAR (255) NULL,
    [Ifrsenable]          NVARCHAR (255) NULL,
    [Ownership]           NVARCHAR (255) NULL,
    [Mgmtcomm]            NVARCHAR (255) NULL,
    [BldgMatrixOption]    NVARCHAR (255) NULL,
    [MatrixId]            NVARCHAR (255) NULL,
    [Trns_Dttm]           NVARCHAR (255) NULL,
    [ProdCode]            FLOAT (53)     NULL,
    [EnviroFlag]          NVARCHAR (255) NULL,
    [Baseuom]             NVARCHAR (255) NULL,
    [Alternateuom]        NVARCHAR (255) NULL,
    [UseAlternateuom]     NVARCHAR (255) NULL,
    [FedId]               NVARCHAR (255) NULL,
    [Map]                 NVARCHAR (255) NULL,
    [BCatId]              NVARCHAR (255) NULL,
    [FmChk]               NVARCHAR (255) NULL,
    [PmChk]               NVARCHAR (255) NULL,
    [FinChk]              NVARCHAR (255) NULL,
    [FmNote]              NVARCHAR (255) NULL,
    [PmNote]              NVARCHAR (255) NULL,
    [FinNote]             NVARCHAR (255) NULL,
    [OwnType]             NVARCHAR (255) NULL,
    [ClarityBldg]         NVARCHAR (255) NULL,
    [CCouncil]            NVARCHAR (255) NULL,
    [PropSubType]         NVARCHAR (255) NULL,
    [SrvcCred]            NVARCHAR (255) NULL,
    [SrvcDebt]            NVARCHAR (255) NULL,
    [AllowPartPmnt]       NVARCHAR (255) NULL,
    [AllowCredit]         NVARCHAR (255) NULL,
    [AllowCreditApply]    NVARCHAR (255) NULL,
    [LogoRef]             NVARCHAR (255) NULL,
    [AchProvider]         NVARCHAR (255) NULL,
    [CcProvider]          NVARCHAR (255) NULL,
    [ReccProvider]        NVARCHAR (255) NULL,
    [InvoiceTo]           NVARCHAR (255) NULL,
    [Site]                NVARCHAR (255) NULL,
    [StmtType]            NVARCHAR (255) NULL,
    [DisplayProviderLogo] NVARCHAR (255) NULL,
    [RapidBldg]           NVARCHAR (255) NULL,
    [RapidDate]           NVARCHAR (255) NULL,
    [MgmtAggr]            NVARCHAR (255) NULL,
    [Measurbl]            NVARCHAR (255) NULL,
    [Well]                NVARCHAR (255) NULL,
    [Country]             NVARCHAR (255) NULL,
    [BldgUse]             NVARCHAR (255) NULL,
    [FmOnly]              NVARCHAR (255) NULL,
    [UrbBldg]             NVARCHAR (255) NULL,
    [SegmentId]           NVARCHAR (255) NULL,
    [Plalloc]             NVARCHAR (255) NULL
);


GO
PRINT N'Creating Table [dbo].[CollegeInfo]...';


GO
CREATE TABLE [dbo].[CollegeInfo] (
    [col_code] CHAR (5)      NOT NULL,
    [col_name] VARCHAR (100) NOT NULL,
    [address1] VARCHAR (150) NULL,
    [address2] VARCHAR (150) NULL,
    [pincode]  VARCHAR (6)   NOT NULL,
    [city]     VARCHAR (50)  NOT NULL,
    [state]    VARCHAR (50)  NOT NULL,
    [uni_code] CHAR (5)      NOT NULL,
    [AffType]  VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([col_code] ASC)
);


GO
PRINT N'Creating Table [dbo].[CourseInfo]...';


GO
CREATE TABLE [dbo].[CourseInfo] (
    [co_code]      CHAR (5)      NOT NULL,
    [co_name]      VARCHAR (100) NOT NULL,
    [deg_code]     CHAR (10)     NOT NULL,
    [sub_code]     CHAR (10)     NOT NULL,
    [col_code]     CHAR (5)      NOT NULL,
    [Sem]          TINYINT       NOT NULL,
    [IsInternship] BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([co_code] ASC)
);


GO
PRINT N'Creating Table [dbo].[DegreeInfo]...';


GO
CREATE TABLE [dbo].[DegreeInfo] (
    [deg_code] CHAR (5)      NOT NULL,
    [deg_name] VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([deg_code] ASC)
);


GO
PRINT N'Creating Table [dbo].[demoempdestination]...';


GO
CREATE TABLE [dbo].[demoempdestination] (
    [id]              INT           NULL,
    [employee_name]   VARCHAR (MAX) NULL,
    [employee_salary] INT           NULL,
    [employee_age]    INT           NULL,
    [profile_image]   VARCHAR (MAX) NULL
);


GO
PRINT N'Creating Table [dbo].[demoempmain]...';


GO
CREATE TABLE [dbo].[demoempmain] (
    [id]              INT           NULL,
    [employee_name]   VARCHAR (MAX) NULL,
    [employee_salary] INT           NULL,
    [employee_age]    INT           NULL,
    [profile_image]   VARCHAR (MAX) NULL
);


GO
PRINT N'Creating Table [dbo].[emp]...';


GO
CREATE TABLE [dbo].[emp] (
    [id]              INT           NULL,
    [employee_name]   VARCHAR (MAX) NULL,
    [employee_salary] INT           NULL,
    [employee_age]    INT           NULL,
    [profile_image]   VARCHAR (MAX) NOT NULL
);


GO
PRINT N'Creating Table [dbo].[file_source22]...';


GO
CREATE TABLE [dbo].[file_source22] (
    [FileId]         INT          NULL,
    [FileName]       VARCHAR (30) NULL,
    [lastmodifytime] VARCHAR (25) NULL
);


GO
PRINT N'Creating Table [dbo].[MRI_Bldg]...';


GO
CREATE TABLE [dbo].[MRI_Bldg] (
    [BldgId]              CHAR (6)        NOT NULL,
    [BldgName]            CHAR (40)       NULL,
    [City]                CHAR (30)       NULL,
    [State]               CHAR (3)        NULL,
    [ZipCode]             CHAR (9)        NULL,
    [LlrdId]              CHAR (6)        NOT NULL,
    [PayTo]               CHAR (30)       NULL,
    [Bldggla]             MONEY           NULL,
    [Sdintrst]            MONEY           NULL,
    [Address1]            CHAR (50)       NULL,
    [Address2]            CHAR (30)       NULL,
    [PhoneNo]             CHAR (15)       NULL,
    [BillDate]            DATETIME        NULL,
    [NmbrUnit]            INT             NULL,
    [MngrId]              CHAR (6)        NOT NULL,
    [Mgrstdat]            DATETIME        NULL,
    [Mgrexdat]            DATETIME        NULL,
    [Prtstat]             CHAR (1)        NOT NULL,
    [DayDue]              SMALLINT        NULL,
    [DelqDay]             SMALLINT        NULL,
    [DelqOpt]             CHAR (1)        NULL,
    [LateFlat]            MONEY           NULL,
    [LateRate]            FLOAT (53)      NULL,
    [LateCalc]            CHAR (1)        NULL,
    [MgmtRate]            FLOAT (53)      NULL,
    [NcFlag]              CHAR (1)        NOT NULL,
    [LastDate]            DATETIME        NULL,
    [UserId]              CHAR (20)       NULL,
    [Inactive]            CHAR (1)        NOT NULL,
    [ICashTyp]            CHAR (2)        NULL,
    [DCashTyp]            CHAR (2)        NULL,
    [CpiIndex]            CHAR (4)        NULL,
    [PtwId]               CHAR (4)        NULL,
    [EntityId]            CHAR (6)        NOT NULL,
    [AltAddr1]            CHAR (50)       NULL,
    [AltAddr2]            CHAR (50)       NULL,
    [AltCity]             CHAR (30)       NULL,
    [AltState]            CHAR (3)        NULL,
    [AltZip]              CHAR (9)        NULL,
    [CloseDay]            CHAR (3)        NOT NULL,
    [FedidTyp]            CHAR (1)        NOT NULL,
    [Feemeth]             CHAR (1)        NOT NULL,
    [FlatAmt]             MONEY           NULL,
    [MgmtAcc]             CHAR (12)       NULL,
    [MgmtCash]            CHAR (2)        NULL,
    [RefndAcc]            CHAR (12)       NULL,
    [Refndcas]            CHAR (2)        NULL,
    [SecurAcc]            CHAR (12)       NULL,
    [Securcas]            CHAR (2)        NULL,
    [County]              CHAR (15)       NULL,
    [AltCount]            CHAR (15)       NULL,
    [ProcDate]            DATETIME        NULL,
    [Cmintrac]            CHAR (12)       NULL,
    [OccSuite]            INT             NULL,
    [Occgla]              MONEY           NULL,
    [GlDetail]            CHAR (1)        NOT NULL,
    [StartInv]            INT             NULL,
    [Fasb13]              CHAR (1)        NOT NULL,
    [SqftType]            CHAR (3)        NULL,
    [Fasbstrt]            DATETIME        NULL,
    [Profile]             CHAR (2)        NULL,
    [WoIncCat]            CHAR (3)        NULL,
    [MarkUp]              MONEY           NULL,
    [MincCat]             CHAR (3)        NULL,
    [TickForm]            CHAR (2)        NULL,
    [ScanCodeId]          CHAR (3)        NULL,
    [Rptypri1]            CHAR (3)        NULL,
    [Rptypri2]            CHAR (3)        NULL,
    [Rptypri3]            CHAR (3)        NULL,
    [Rptypri4]            CHAR (3)        NULL,
    [Rptypri5]            CHAR (3)        NULL,
    [BilLevel]            CHAR (3)        NULL,
    [EstLevel]            CHAR (3)        NULL,
    [RecLevel]            CHAR (3)        NULL,
    [Natural]             CHAR (1)        NOT NULL,
    [NincCat1]            CHAR (3)        NULL,
    [NincCat2]            CHAR (3)        NULL,
    [NincCat3]            CHAR (3)        NULL,
    [Estmeth]             CHAR (3)        NULL,
    [BillPnt]             CHAR (1)        NOT NULL,
    [Calcest]             CHAR (1)        NOT NULL,
    [Reqrpty]             CHAR (3)        NULL,
    [ForeType]            CHAR (3)        NULL,
    [PercChng]            MONEY           NULL,
    [Retail]              CHAR (1)        NULL,
    [NrecId]              CHAR (6)        NULL,
    [Basis]               CHAR (1)        NULL,
    [Mgmtnont]            CHAR (1)        NULL,
    [Mgmtsecapp]          CHAR (1)        NULL,
    [Mgmtcrapp]           CHAR (1)        NULL,
    [MgmtVendId]          CHAR (6)        NULL,
    [LtfeeDays]           SMALLINT        NULL,
    [LtfcAmt]             MONEY           NULL,
    [CarPark]             SMALLINT        NULL,
    [Mobile]              CHAR (15)       NULL,
    [Fax]                 CHAR (15)       NULL,
    [Email]               CHAR (35)       NULL,
    [ContName]            CHAR (30)       NULL,
    [RangeType]           CHAR (1)        NULL,
    [MgmtDept]            CHAR (3)        NULL,
    [MgmtrTaxGrp]         CHAR (1)        NULL,
    [PropId]              CHAR (3)        NULL,
    [Revmethod1]          CHAR (5)        NULL,
    [ReviewDate]          DATETIME        NULL,
    [Recovered]           CHAR (3)        NULL,
    [MgmtAct]             CHAR (1)        NULL,
    [BatchName]           CHAR (10)       NULL,
    [InactiveDate]        CHAR (6)        NULL,
    [Autoreport]          CHAR (1)        NULL,
    [MgmtBillflat]        CHAR (1)        NULL,
    [Days]                FLOAT (53)      NOT NULL,
    [OwnCopy]             CHAR (1)        NULL,
    [AltMngrId]           CHAR (6)        NULL,
    [ReportBasis]         CHAR (1)        NULL,
    [SscStaffId]          CHAR (6)        NULL,
    [ProRata]             CHAR (1)        NULL,
    [OType]               CHAR (2)        NULL,
    [FoBldg]              CHAR (1)        NULL,
    [Class]               CHAR (6)        NULL,
    [MerchantId]          CHAR (6)        NULL,
    [MerchantPassword]    CHAR (8)        NULL,
    [RecpttypeId]         CHAR (3)        NULL,
    [BApplyByPriority]    CHAR (1)        NULL,
    [URL]                 CHAR (50)       NULL,
    [AttachId]            CHAR (8)        NULL,
    [Agent]               CHAR (10)       NULL,
    [CommenceDate]        CHAR (6)        NULL,
    [LastmngrId]          CHAR (6)        NULL,
    [ReasonCode]          CHAR (4)        NULL,
    [Ifrsenable]          CHAR (1)        NULL,
    [Ownership]           CHAR (5)        NULL,
    [Mgmtcomm]            TEXT            NULL,
    [BldgMatrixOption]    CHAR (1)        NULL,
    [MatrixId]            FLOAT (53)      NULL,
    [Trns_Dttm]           DATETIME        NULL,
    [ProdCode]            CHAR (2)        NOT NULL,
    [EnviroFlag]          CHAR (1)        NULL,
    [Baseuom]             CHAR (6)        NULL,
    [Alternateuom]        CHAR (6)        NULL,
    [UseAlternateuom]     CHAR (1)        NULL,
    [FedId]               VARBINARY (MAX) NULL,
    [Map]                 CHAR (500)      NULL,
    [BCatId]              CHAR (7)        NULL,
    [FmChk]               CHAR (1)        NULL,
    [PmChk]               CHAR (1)        NULL,
    [FinChk]              CHAR (1)        NULL,
    [FmNote]              CHAR (50)       NULL,
    [PmNote]              CHAR (50)       NULL,
    [FinNote]             CHAR (50)       NULL,
    [OwnType]             CHAR (10)       NULL,
    [ClarityBldg]         CHAR (1)        NULL,
    [CCouncil]            CHAR (40)       NULL,
    [PropSubType]         CHAR (3)        NULL,
    [SrvcCred]            CHAR (12)       NULL,
    [SrvcDebt]            CHAR (12)       NULL,
    [AllowPartPmnt]       CHAR (1)        NULL,
    [AllowCredit]         CHAR (1)        NULL,
    [AllowCreditApply]    CHAR (1)        NULL,
    [LogoRef]             VARCHAR (50)    NULL,
    [AchProvider]         CHAR (20)       NULL,
    [CcProvider]          CHAR (20)       NULL,
    [ReccProvider]        CHAR (20)       NULL,
    [InvoiceTo]           CHAR (100)      NULL,
    [Site]                CHAR (20)       NULL,
    [StmtType]            CHAR (10)       NULL,
    [DisplayProviderLogo] CHAR (1)        NOT NULL,
    [RapidBldg]           CHAR (1)        NULL,
    [RapidDate]           DATETIME        NULL,
    [MgmtAggr]            CHAR (12)       NULL,
    [Measurbl]            CHAR (1)        NULL,
    [Well]                CHAR (1)        NULL,
    [Country]             CHAR (15)       NULL,
    [BldgUse]             CHAR (15)       NULL,
    [FmOnly]              CHAR (1)        NULL,
    [UrbBldg]             CHAR (1)        NULL,
    [SegmentId]           CHAR (10)       NULL,
    [Plalloc]             CHAR (10)       NULL,
    CONSTRAINT [Upkcl_Bldg] PRIMARY KEY CLUSTERED ([BldgId] ASC)
);


GO
PRINT N'Creating Table [dbo].[paypal_invoices]...';


GO
CREATE TABLE [dbo].[paypal_invoices] (
    [invoice_id]              NVARCHAR (50) NULL,
    [currency_code]           NVARCHAR (50) NULL,
    [invoice_number]          INT           NULL,
    [invoice_date]            DATE          NULL,
    [payment_due_date]        DATE          NULL,
    [creation_date]           DATETIME      NULL,
    [invoicer_email_address]  NVARCHAR (50) NULL,
    [recipient_email_address] NVARCHAR (50) NULL,
    [amount]                  MONEY         NULL,
    [due_amount]              MONEY         NULL
);


GO
PRINT N'Creating Table [dbo].[ProfessorInfo]...';


GO
CREATE TABLE [dbo].[ProfessorInfo] (
    [prof_code] CHAR (5)      NOT NULL,
    [prof_name] VARCHAR (100) NOT NULL,
    [address1]  VARCHAR (150) NULL,
    [address2]  VARCHAR (150) NULL,
    [pincode]   VARCHAR (6)   NOT NULL,
    [city]      VARCHAR (50)  NOT NULL,
    [state]     VARCHAR (50)  NOT NULL,
    [col_code]  CHAR (5)      NOT NULL,
    PRIMARY KEY CLUSTERED ([prof_code] ASC)
);


GO
PRINT N'Creating Table [dbo].[RPD_Site]...';


GO
CREATE TABLE [dbo].[RPD_Site] (
    [UID]             INT           IDENTITY (1, 1) NOT NULL,
    [SiteId]          INT           NULL,
    [Deleted]         BIT           NULL,
    [Modified]        DATETIME      NULL,
    [Country]         VARCHAR (100) NULL,
    [StateId]         INT           NULL,
    [Name]            VARCHAR (100) NULL,
    [BuildingId]      CHAR (6)      NULL,
    [Street]          VARCHAR (100) NULL,
    [Town]            VARCHAR (100) NULL,
    [ExternalStateId] INT           NULL,
    [LastModifyTime]  DATETIME      NULL,
    CONSTRAINT [PK_Site] PRIMARY KEY CLUSTERED ([UID] ASC)
);


GO
PRINT N'Creating Table [dbo].[RPD_State]...';


GO
CREATE TABLE [dbo].[RPD_State] (
    [UID]                     INT           IDENTITY (1, 1) NOT NULL,
    [StateId]                 INT           NULL,
    [StateName]               VARCHAR (100) NULL,
    [AdminId]                 INT           NULL,
    [DivisionId]              INT           NULL,
    [WorkCoverExempt]         BIT           NULL,
    [Code]                    VARCHAR (100) NULL,
    [IsShowCr]                BIT           NULL,
    [IsShowSwms]              BIT           NULL,
    [IsShowWci]               BIT           NULL,
    [IsShowIssuePasswordPage] BIT           NULL,
    [LastModifyTime]          DATETIME      NULL,
    CONSTRAINT [PK_State] PRIMARY KEY CLUSTERED ([UID] ASC)
);


GO
PRINT N'Creating Table [dbo].[State$]...';


GO
CREATE TABLE [dbo].[State$] (
    [UID]                     FLOAT (53)     NULL,
    [StateId]                 FLOAT (53)     NULL,
    [StateName]               NVARCHAR (255) NULL,
    [AdminId]                 FLOAT (53)     NULL,
    [DivisionId]              FLOAT (53)     NULL,
    [WorkCoverExempt]         FLOAT (53)     NULL,
    [Code]                    NVARCHAR (255) NULL,
    [IsShowCr]                FLOAT (53)     NULL,
    [IsShowSwms]              FLOAT (53)     NULL,
    [IsShowWci]               FLOAT (53)     NULL,
    [IsShowIssuePasswordPage] FLOAT (53)     NULL,
    [LastModifyTime]          DATETIME       NULL
);


GO
PRINT N'Creating Table [dbo].[StudentInfo]...';


GO
CREATE TABLE [dbo].[StudentInfo] (
    [st_code]  CHAR (5)       NOT NULL,
    [st_name]  VARCHAR (100)  NOT NULL,
    [address1] VARCHAR (150)  NULL,
    [address2] VARCHAR (150)  NULL,
    [pincode]  VARCHAR (6)    NOT NULL,
    [city]     VARCHAR (50)   NOT NULL,
    [state]    VARCHAR (50)   NOT NULL,
    [co_code]  CHAR (5)       NOT NULL,
    [DOB]      DATE           NOT NULL,
    [Optional] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([st_code] ASC)
);


GO
PRINT N'Creating Table [dbo].[StudentInfoFinal]...';


GO
CREATE TABLE [dbo].[StudentInfoFinal] (
    [st_code]  CHAR (5)      NOT NULL,
    [st_name]  VARCHAR (100) NOT NULL,
    [address1] VARCHAR (150) NULL,
    [address2] VARCHAR (150) NULL,
    [pincode]  VARCHAR (6)   NOT NULL,
    [city]     VARCHAR (50)  NOT NULL,
    [state]    VARCHAR (50)  NOT NULL,
    [co_code]  CHAR (5)      NOT NULL,
    [DOB]      DATE          NOT NULL,
    PRIMARY KEY CLUSTERED ([st_code] ASC)
);


GO
PRINT N'Creating Table [dbo].[SubjectInfo]...';


GO
CREATE TABLE [dbo].[SubjectInfo] (
    [sub_code] CHAR (5)      NOT NULL,
    [sub_name] VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([sub_code] ASC)
);


GO
PRINT N'Creating Table [dbo].[Table1]...';


GO
CREATE TABLE [dbo].[Table1] (
    [Id] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[temp]...';


GO
CREATE TABLE [dbo].[temp] (
    [Serial] NUMERIC (5) NOT NULL,
    [name1]  CHAR (5)    NULL,
    [name2]  VARCHAR (5) NULL,
    PRIMARY KEY CLUSTERED ([Serial] ASC)
);


GO
PRINT N'Creating Table [dbo].[testmain]...';


GO
CREATE TABLE [dbo].[testmain] (
    [id] INT NULL
);


GO
PRINT N'Creating Table [dbo].[UniversityInfo]...';


GO
CREATE TABLE [dbo].[UniversityInfo] (
    [uni_code] CHAR (5)      NOT NULL,
    [uni_name] VARCHAR (100) NOT NULL,
    [address1] VARCHAR (150) NULL,
    [address2] VARCHAR (150) NULL,
    [pincode]  VARCHAR (6)   NOT NULL,
    [city]     VARCHAR (50)  NOT NULL,
    [state]    VARCHAR (50)  NOT NULL,
    [UniType]  VARCHAR (50)  NOT NULL,
    PRIMARY KEY CLUSTERED ([uni_code] ASC)
);


GO
PRINT N'Creating Table [dbo].[watermarktable]...';


GO
CREATE TABLE [dbo].[watermarktable] (
    [TableName]      VARCHAR (40) NULL,
    [WatermarkValue] DATETIME     NULL
);


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[MRI_Bldg]...';


GO
ALTER TABLE [dbo].[MRI_Bldg]
    ADD DEFAULT ('N') FOR [AllowPartPmnt];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[MRI_Bldg]...';


GO
ALTER TABLE [dbo].[MRI_Bldg]
    ADD DEFAULT ('N') FOR [AllowCredit];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[MRI_Bldg]...';


GO
ALTER TABLE [dbo].[MRI_Bldg]
    ADD DEFAULT ('N') FOR [AllowCreditApply];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[MRI_Bldg]...';


GO
ALTER TABLE [dbo].[MRI_Bldg]
    ADD DEFAULT ('Y') FOR [DisplayProviderLogo];


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[CollegeInfo]...';


GO
ALTER TABLE [dbo].[CollegeInfo] WITH NOCHECK
    ADD FOREIGN KEY ([uni_code]) REFERENCES [dbo].[UniversityInfo] ([uni_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[CourseInfo]...';


GO
ALTER TABLE [dbo].[CourseInfo] WITH NOCHECK
    ADD FOREIGN KEY ([col_code]) REFERENCES [dbo].[CollegeInfo] ([col_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[ProfessorInfo]...';


GO
ALTER TABLE [dbo].[ProfessorInfo] WITH NOCHECK
    ADD FOREIGN KEY ([col_code]) REFERENCES [dbo].[CollegeInfo] ([col_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[StudentInfo]...';


GO
ALTER TABLE [dbo].[StudentInfo] WITH NOCHECK
    ADD FOREIGN KEY ([co_code]) REFERENCES [dbo].[CourseInfo] ([co_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[StudentInfo]...';


GO
ALTER TABLE [dbo].[StudentInfo] WITH NOCHECK
    ADD FOREIGN KEY ([co_code]) REFERENCES [dbo].[CourseInfo] ([co_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[StudentInfo]...';


GO
ALTER TABLE [dbo].[StudentInfo] WITH NOCHECK
    ADD FOREIGN KEY ([co_code]) REFERENCES [dbo].[CourseInfo] ([co_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[StudentInfo]...';


GO
ALTER TABLE [dbo].[StudentInfo] WITH NOCHECK
    ADD FOREIGN KEY ([co_code]) REFERENCES [dbo].[CourseInfo] ([co_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[StudentInfo]...';


GO
ALTER TABLE [dbo].[StudentInfo] WITH NOCHECK
    ADD FOREIGN KEY ([co_code]) REFERENCES [dbo].[CourseInfo] ([co_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[StudentInfo]...';


GO
ALTER TABLE [dbo].[StudentInfo] WITH NOCHECK
    ADD FOREIGN KEY ([co_code]) REFERENCES [dbo].[CourseInfo] ([co_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[StudentInfo]...';


GO
ALTER TABLE [dbo].[StudentInfo] WITH NOCHECK
    ADD FOREIGN KEY ([co_code]) REFERENCES [dbo].[CourseInfo] ([co_code]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[StudentInfo]...';


GO
ALTER TABLE [dbo].[StudentInfo] WITH NOCHECK
    ADD FOREIGN KEY ([co_code]) REFERENCES [dbo].[CourseInfo] ([co_code]);


GO
PRINT N'Creating Procedure [dbo].[update_watermark_table]...';


GO

CREATE procedure [dbo].[update_watermark_table] @lastmodifytime datetime, @Tablename varchar(40)
AS
BEGIN

update watermarktable
set [WatermarkValue]= @lastmodifytime
where [TableName]=@Tablename

END
GO
PRINT N'Creating Procedure [dbo].[updaterpd]...';


GO
create procedure [dbo].[updaterpd] as
  declare @counter INT;
  declare @start INT=1;
  SET @counter= (select count(*) from RPD_Site)
  WHILE @start<@counter
  begin      
  update RPD_Site 
  set BuildingId=	
  CASE 
			WHEN ISNUMERIC(SUBSTRING([Name],1,6))='1'
			THEN SUBSTRING([Name],1,6) 
			ELSE NULL
			END 
		--	(SELECT  
		--SUBSTRING(Name,1,6) 
		--from RPD_Site 
		--where BuildingId is null 
		--and  UID= @start)
  where UID=@start and BuildingId is null
  set @start=@start+1;
  end
GO
PRINT N'Creating Procedure [dbo].[updtdrpdsitebuildingidnull]...';


GO
create  procedure updtdrpdsitebuildingidnull As
  select rs.BuildingId ,rs.Name 
  from RPD_Site rs
  where rs.BuildingId is Null

  begin
    update RPD_Site set BuildingId=(SELECT  SUBSTRING(Name,1,6) from RPD_Site where UID=1)
 where UID=1
  end
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
CREATE TABLE [#__checkStatus] (
    id           INT            IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
    [Schema]     NVARCHAR (256),
    [Table]      NVARCHAR (256),
    [Constraint] NVARCHAR (256)
);

SET NOCOUNT ON;

DECLARE tableconstraintnames CURSOR LOCAL FORWARD_ONLY
    FOR SELECT SCHEMA_NAME([schema_id]),
               OBJECT_NAME([parent_object_id]),
               [name],
               0
        FROM   [sys].[objects]
        WHERE  [parent_object_id] IN (OBJECT_ID(N'dbo.CollegeInfo'), OBJECT_ID(N'dbo.CourseInfo'), OBJECT_ID(N'dbo.ProfessorInfo'), OBJECT_ID(N'dbo.StudentInfo'))
               AND [type] IN (N'F', N'C')
                   AND [object_id] IN (SELECT [object_id]
                                       FROM   [sys].[check_constraints]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0
                                       UNION
                                       SELECT [object_id]
                                       FROM   [sys].[foreign_keys]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0);

DECLARE @schemaname AS NVARCHAR (256);

DECLARE @tablename AS NVARCHAR (256);

DECLARE @checkname AS NVARCHAR (256);

DECLARE @is_not_trusted AS INT;

DECLARE @statement AS NVARCHAR (1024);

BEGIN TRY
    OPEN tableconstraintnames;
    FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
    WHILE @@fetch_status = 0
        BEGIN
            PRINT N'Checking constraint: ' + @checkname + N' [' + @schemaname + N'].[' + @tablename + N']';
            SET @statement = N'ALTER TABLE [' + @schemaname + N'].[' + @tablename + N'] WITH ' + CASE @is_not_trusted WHEN 0 THEN N'CHECK' ELSE N'NOCHECK' END + N' CHECK CONSTRAINT [' + @checkname + N']';
            BEGIN TRY
                EXECUTE [sp_executesql] @statement;
            END TRY
            BEGIN CATCH
                INSERT  [#__checkStatus] ([Schema], [Table], [Constraint])
                VALUES                  (@schemaname, @tablename, @checkname);
            END CATCH
            FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
        END
END TRY
BEGIN CATCH
    PRINT ERROR_MESSAGE();
END CATCH

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') >= 0
    CLOSE tableconstraintnames;

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') = -1
    DEALLOCATE tableconstraintnames;

SELECT N'Constraint verification failed:' + [Schema] + N'.' + [Table] + N',' + [Constraint]
FROM   [#__checkStatus];

IF @@ROWCOUNT > 0
    BEGIN
        DROP TABLE [#__checkStatus];
        RAISERROR (N'An error occurred while verifying constraints', 16, 127);
    END

SET NOCOUNT OFF;

DROP TABLE [#__checkStatus];


GO
PRINT N'Update complete.';


GO
